upstream auth {
    server auth:5000;
    keepalive 32;
}
server {
    listen 8080;
    server_name localhost; 
    
    # Frontend Service
    location / {
        proxy_pass http://frontend:5173;
    }
    # Authentication Service
    location = /auth/verify {
        proxy_pass http://auth;
    }   

    location /api/auth/ {
        proxy_pass http://auth;
        proxy_set_header Cookie $http_cookie;
    }


    # User Management Service
    location /api/users/ {
        if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' 'http://localhost:5173' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, x-user-id, x-user' always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        add_header 'Content-Length' 0;
        return 204;
    }
        auth_request /auth/verify;
        
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        proxy_set_header x-user-id $user_id;
        proxy_set_header x-user $user;

        
        proxy_pass http://user-management:3000/;
    }
    
    location /uploads/ {
    proxy_pass http://user-management:3000/uploads/;
    }

    location /api/chat/ {
        auth_request /auth/verify/;
        
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    #tournament service
    location /tournament/ {
        auth_request /auth/verify;  

        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        
        proxy_set_header x-user-id $user_id;
        proxy_set_header x-user $user;
        proxy_pass http://tournament:5500;
    }

    # 2FA Service
    location /2f/
    {
        auth_request /auth/verify;  

        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        
        proxy_set_header x-user-id $user_id;
        proxy_set_header x-user $user;
        proxy_pass http://auth;
    }

    # Healthcheck
    location /health {
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
