upstream auth {
    server auth:5000;
    keepalive 32;
}

server {
    listen 8080;
    server_name localhost; 

    # Authentication Service
    location = /auth/verify/ {
        proxy_pass http://auth/verify;
        # proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }
    
    location /api/auth/ {
        proxy_pass http://auth;  # ✅ no port here!
    }

    # User Management Service
    location /api/users/ {
        auth_request /auth/verify/;
        
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        
        proxy_set_header x-user-id $user_id;
        proxy_set_header x-user $user;
        proxy_pass http://user-management:3000/;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /socket.io/ {
        auth_request /auth/verify/;
        
        auth_request_set $user_id $upstream_http_x_user_id;
        auth_request_set $user $upstream_http_x_user;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        # auth_request /auth/verify/; 
        # auth_request_set $user_id $upstream_http_x_user_id;
        # auth_request_set $user $upstream_http_x_user;
        
        proxy_pass http://chat:3000/socket.io/;
    }

    # location /api/chat/ {
    #     auth_request /auth/verify/;
        
    #     auth_request_set $user_id $upstream_http_x_user_id;
    #     auth_request_set $user $upstream_http_x_user;
        
    #     proxy_set_header x-user-id $user_id;
    #     proxy_set_header x-user $user;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_http_version 1.1;
        
    #     proxy_pass http://chat:3000/socket.io/;
    # }


    # Health check endpoint (optional)
    location /health {
        return 200 "OK";
        add_header Content-Type text/plain;
    }

}