# version: '3.8'
services:
  user_management:
    build: ./user-management
    container_name: user_management
    ports:
      - "3000:3000"
    volumes:
      - ./user-management/src:/usr/src/app/src
      - ./user-management/public:/usr/src/app/public  #just for testing 
      - ./user-management/PINGPONG.db:/usr/src/app/PINGPONG.db
    command: npm run dev
